# Generated by Django 5.0.6 on 2024-06-28 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_director_programa', models.BooleanField(default=False, verbose_name='director status')),
                ('is_docente', models.BooleanField(default=False, verbose_name='docente status')),
                ('is_daca', models.BooleanField(default=False, verbose_name='daca status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('comentario_limpio', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('sentimiento', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('escuela', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Daca',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='daca', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorPrograma',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='director_programa', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('escuela', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField()),
                ('semestre', models.CharField(max_length=10)),
                ('anho', models.IntegerField()),
                ('comentario', models.ForeignKey(db_column='comentario_id', on_delete=django.db.models.deletion.CASCADE, to='core.comentario')),
                ('materia', models.ForeignKey(db_column='materia_codigo', on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
                ('docente', models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
            ],
            options={
                'unique_together': {('comentario', 'docente')},
            },
        ),
    ]
