# Generated by Django 5.0.6 on 2024-07-02 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentario',
            field=models.ForeignKey(db_column='comentario_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_comentario', to='core.comentario'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='docente',
            field=models.ForeignKey(db_column='docente_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to='core.docente'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(db_column='materia_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_materia', to='core.materia'),
        ),
    ]
